In [10]:
!pwd

/content

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
import pandas as pd
df_books = pd.read_csv('/content/drive/MyDrive/PANDA/libros.csv')
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

## SCLICING

In [12]:
df_books[10:12]

,Name,Author,User Rating,Reviews,Price,Year,Genre
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,2,2010,Non Fiction

In [13]:
df_books[['Name','Author']]

,Name,Author
0,10-Day Green Smoothie Cleanse,JJ Smith
1,11/22/63: A Novel,Stephen King
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson
3,1984 (Signet Classics),George Orwell
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids
...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero

##LOC

In [14]:
df_books.loc[0:4,['Name','Author']]

                                                Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [15]:
df_books.loc[:,['Reviews']] * -1

     Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [16]:
df_books.loc[:,['Author']] == 'JJ Smith'

     Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

##ILOC

In [21]:
df_books.iloc[0:2,0:4]

                            Name        Author  User Rating  Reviews
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350
1              11/22/63: A Novel  Stephen King          4.6     2052

In [20]:
df_books.iloc[1,3] * -1

-2052

In [22]:
df_books.iloc[:2,2:5]

   User Rating  Reviews  Price
0          4.7    17350      8
1          4.6     2052     22